# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12Yy3uVBsxtNNdohbnIEsoRr5Cmf86XGw

#Importing the libraries
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import svm
from sklearn import metrics
import joblib
from sklearn.decomposition import PCA
from sklearn.utils import shuffle

"""#Reading the dataset"""

dataframe=pd.read_csv('dataset6labels.csv')
dataframe=dataframe.sample(frac=1).reset_index(drop=True)

"""#Print Dataframe"""

X=dataframe.drop(['label'],axis=1)
Y=dataframe['label']
print(X)
print(Y)

"""#Splitting the dataframe into training set and test set"""

X_train,Y_train=X[0:198],Y[0:198]
X_test,Y_test=X[198:],Y[198:]
print(X_train)
print(X_test)
print(Y_train)
print(Y_test)

"""#Displaying the graph"""

grid_data=X_train.values[40].reshape(28,28)
plt.imshow(grid_data,interpolation=None,cmap="gray")
plt.title(Y_train.values[40])
plt.show()

"""#Fitting the training set to SVM model"""

model=svm.SVC(kernel="linear",C=2)
print("fitting the model.......")
model.fit(X_train,Y_train)

"""#Saving the model for further use using joblib"""

joblib.dump(model,"svm_6label_linear_2")
print("Predicting......")
predictions=model.predict(X_test)

"""#To check accuracy of our model fitted"""

print ("Getting Accuracy .....")
print ("Score", metrics.accuracy_score(Y_test, predictions))