# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gZ3Og0FeLm3yxfqg3XHvhruPLPtTsijM

#importing the libraries
"""

import pyscreenshot as ImageGrab
import time

"""#making of folder for storage"""

image_folder="orig_images.zip"

"""#screen capture"""

for i in range (0,45):
  time.sleep(5)
  im=ImageGrab.grab(bbox=(80,80,208,208))#X1,Y1,X2,Y2
  print("saved....",i)
  im.save(images_folder+str(i)+'.png')
  print("clear screen now and redraw now....")